package pt.uc.dei.proj5.websockets;

import jakarta.inject.Inject;
import jakarta.persistence.Id;
import jakarta.websocket.*;
import jakarta.websocket.server.PathParam;
import jakarta.websocket.server.ServerEndpoint;
import java.io.StringReader;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonReader;
import pt.uc.dei.proj5.beans.UserBean;
import pt.uc.dei.proj5.dao.AdminDao;
import pt.uc.dei.proj5.dao.MessageDao;
import pt.uc.dei.proj5.dto.UserDto;
import pt.uc.dei.proj5.entity.MessageEntity;
import pt.uc.dei.proj5.entity.UserEntity;


@ServerEndpoint("/chat/{id}")
public class ChatEndpoint {

    @Inject
    private AdminDao adminDao;

    @Inject
    private UserBean userBean;

    @Inject
    private MessageDao messageDao;


    private static final Map<Long, Session> chatSessions = new ConcurrentHashMap<>();

    @OnOpen
    public void onOpen(Session session, @PathParam("id") Long senderID) {
        chatSessions.put(senderID, session);
        System.out.println("User joined chat. ID: " + senderID);
    }

    @OnClose
    public void onClose(Session session, @PathParam("id") Long senderID) {
        chatSessions.remove(senderID);
        System.out.println("User left chat. ID: " + senderID);
    }

    @OnError
    public void onError(Session session, Throwable throwable) {
        System.err.println("Chat WebSocket error: " + throwable.getMessage());
    }

    @OnMessage
    public void onMessage(String jsonMessage, @PathParam("id") Long senderID) {
        try (JsonReader reader = Json.createReader(new StringReader(jsonMessage))) {
            JsonObject incomingJson = reader.readObject();
            Long receiverID = incomingJson.getJsonNumber("receiver").longValue();
            String text = incomingJson.getString("text");

            // --- 1. SAVE THE MESSAGE TO THE DATABASE ---
            UserEntity senderEntity = adminDao.getUserByID(senderID);
            UserEntity receiverEntity = adminDao.getUserByID(receiverID);

            if (senderEntity != null && receiverEntity != null) {
                MessageEntity newMsg = new MessageEntity();
                newMsg.setSender(senderEntity);
                newMsg.setReceiver(receiverEntity);
                newMsg.setText(text);

                // Save it! (Timestamp is auto-generated by the PrePersist we added)
                messageDao.saveMessage(newMsg);
            }

            // --- 2. TRY TO SEND VIA WEBSOCKET (If they are online) ---
            Session receiverSession = chatSessions.get(receiverID);
            if (receiverSession != null && receiverSession.isOpen()) {

                // Build the exact JSON your React frontend expects
                JsonObject outgoingJson = Json.createObjectBuilder()
                        .add("sender", senderID)
                        .add("receiver", receiverID)
                        .add("text", text)
                        .build();

                receiverSession.getBasicRemote().sendText(outgoingJson.toString());
            }

            // --- 3. SEND NOTIFICATION BELL (Optional, but good!) ---
            if (senderEntity != null) {
                String notificationMsg = "New message from " + senderEntity.getUsername() + ": " + text;
                NotificationEndpoint.sendNotification(receiverID, notificationMsg);
            }

        } catch (Exception e) {
            System.err.println("Error processing chat message: " + e.getMessage());
        }
    }
}